### ISSUE TITLE
F5 key is not triggering PHPDOX on mac

### ISSUE THREAD

**Issue by raftalks** [oct8cat/sublime-phpdox#3] opened 2012-09-14 12:06 UTC
Hi, I just installed phpdox on my macbook pro with sublime text 2 and it seems the Hot key is not functioning when I simply tried pressing F5 key. I have tried the following key strokes to test.

1) press F5 (mac shortcut for keyboard light appears)
2) press fn+F5 (nothing happened)

**Comment by oct8cat** [comment] 2012-09-14 12:28
@raftalks Hey!

I just added OSX keybindings files, try to update the plugin.
If it is still don't working, maybe the "F5" key is already used by some another command?

Try to place cursor in a line with method declaration, then open console (Cmd + `), type `view.run_command('phpdox')` and press enter. If it works, then you just need to assign `phpdox` command to another hotkey. Go to `Preferences > Key bindings - User` and add the next line to your hotkeys config:

`{ "keys": ["YOURKEY"], "command": "phpdox" }`

where `YOURKEY` is the key you wants to use for PhpDox.

Also, the plugin works ONLY for files with `.php` extension, so be sure you don't trying to write PHP code in some python files :)

Cheers.

**Comment by niluzok** [comment] 2012-09-22 21:14
hi!
I have the same problem and when i do view.run_command('phpdox'), i get 

Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./PhpDox.py", line 68, in run
  File "./PhpDox.py", line 79, in process_line
TypeError: 'NoneType' object is unsubscriptable

what's wrong?

**Comment by oct8cat** [comment] 2012-09-23 11:58
Hey, @brodlo 

I cannot reproduce this issue, but it looks like the plugin can't find or parse patterns for line type resolving from `Base File.sublime-settings` file. Please, show me output of the next command:

```
view.settings().get('phpdox')
```

Also, provide your OS and python version (if you're using custom python):

```
import sys
sys.version
```

**Comment by niluzok** [comment] 2012-09-23 20:16
so, view.settings().get('phpdox') prints nothing...

i dont use custom python, and version is
'2.6.1 (r261:67515, Jun 24 2010, 21:47:49) \n[GCC 4.2.1 (Apple Inc. build 5646)]'

i forgot to say that i moved folders Installed Packages, Packages and Pristine Packages to dropbox and created symlinks to them. may it be a reason?

**Comment by oct8cat** [comment] 2012-09-24 00:00
I'm not sure if it is symlinks issue. I have my sublime settings symlinked too, when physically the folder cloned by git to another directory, and all works fine. But I have the whole sublime directory symlinked, not subfolders. Try to phisically copy your symlinked folders from Dropbox to Sublime directory and check if it will help.

Also, accordings to [Sublime settings docs](http://sublimetext.info/docs/en/customization/settings.html) platform-dependent settings files stores in `Base File (PLATFORM).sublime-settings`, so try to copy `PhpDox/Base File.sublime-settings` to `PhpDox/Base File (OSX).sublime-settings`. If it helps, I will add OSX-specific settings to my repo.

**Comment by niluzok** [comment] 2012-09-24 20:05
oh..i recreated symlinks and the problem disappeared) i changed key binding and...
your package works great!
thanks for attention!

**Comment by oct8cat** [comment] 2012-09-24 20:18
You are welcome :3

**Closed as completed by oct8cat** 2012-09-24 20:18 UTC
Labels: bug
